---
- name: Ensure directory is exists
  file:
    path: "{{ base_dir }}/consul"
    state: directory

########## Agent ##########
- name: Copy compose file for agent
  template:
    src: agent.yml.j2
    dest: "{{ base_dir }}/consul/docker-compose.yml"
  when: consul_type is not defined or (consul_type is defined and consul_type != 'server')

- name: Run consul agent
  command: bash -c "docker stack deploy --compose-file {{ base_dir }}/consul/docker-compose.yml consul"
  when: consul_type is not defined or (consul_type is defined and consul_type != 'server')

########## Server ##########
- name: Copy compose file for server
  template:
    src: server.yml.j2
    dest: "{{ base_dir }}/consul/docker-compose.yml"
  when:
    - consul_type is defined
    - consul_type == 'server'

- name: Run consul server
  command: bash -c "docker stack deploy --compose-file {{ base_dir }}/consul/docker-compose.yml consul"
  when:
    - consul_type is defined
    - consul_type == 'server'
